### PR TITLE
fix(openwhisk): ensure the openwhisk action API is imported via require

### LINKED ISSUE #132: Openhwisk patcher doesn't work when final action is bundled
The problem is the:

```
const actions = tryRequire('openwhisk/lib/actions.js');
```

which hides the dependency from webpack. so in the final bundle, it cannot find the source.

replacing it with an explicit `require` works:

```
let actions;
try {
    // eslint-disable-next-line global-require,import/no-unresolved
    actions = require('openwhisk/lib/actions.js');
} catch (e) {
    // ignore
}
```

### PR DESCRIPTION
**Pull request by tripodsan**
fixes #132

### CODE REVIEW

**Comment by ranrib** [comment]
Hi @tripodsan, We use the tryRequire here (and on other libraries that we instrument) specifically to not force the load. We rely on that `openwhisk` is already provided by you at the packge.json. Isn't it that case?

**Comment by ranrib** [comment]
Also, can you please fork out from `develop`? travis runs some acceptance test that only we can run, so we created develop for external contributions

**Comment by tripodsan** [comment]
> Hi @tripodsan, We use the tryRequire here (and on other libraries that we instrument) specifically to not force the load. We rely on that `openwhisk` is already provided by you at the packge.json. Isn't it that case?

Hi @ranrib, the problem is that we use webpack to bundle our final openwhisk actions. using `tryRequire` hides the import of the `openwhisk/lib/action.js` from webpack and it is not possible to resolve its path. using a _normal_ require (which in turn uses the webpack require) solves this problem.

comparing the two bundles shows the following:

#### the espagon bundle
```diff
$ diff bundle.tryrequire.js bundle.require.js
15a16
> var actions = _interopDefault(require('openwhisk/lib/actions.js'));
13068c13069,13077
< const actions = try_require('openwhisk/lib/actions.js');
```

#### our bundle:
```diff
$ diff testing-bundle.require.js testing-bundle.tryrequire.js
12695a12696
> var actions = _interopDefault(__webpack_require__(/*! openwhisk/lib/actions.js */ "./node_modules/openwhisk/lib/actions.js"));
25748c25749,25757
< const actions = try_require('openwhisk/lib/actions.js');
```

The problem is that the `tryRequire()` gets transformed by webpack to:

```
    const currentRequire = req || __webpack_require__("./node_modules/epsagon/dist sync recursive");
```

so it only uses the module path of the `epsagon/dist` module.

**Comment by tripodsan** [comment]
> Also, can you please fork out from develop

I would, but `develop` doesn't contain the latest code.

**Comment by ranrib** [comment]
👍 taken care in #134

**Pull request closed without merging**
