### PR TITLE
feat(sns-batch): add support for sns publishBatch

### PR DESCRIPTION
**Pull request by ymwjbxxq**
AWS announced the is now possible to [publish messages in batch](https://aws.amazon.com/blogs/compute/publishing-messages-in-batch-to-amazon-sns-topics/) to Amazon SNS topics

I have added the support following the interface visible [here](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SNS.html#publishBatch-property)

I have also updated the aws-sdk npm package to [Lambda supported runtime](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html) 2.1001.0

### CODE REVIEW

**Review by haddasbronfman — COMMENTED** [review]
Hi Dan, and thank you for your contribution!
It seems good for delivery. 

Could you please add test here ?
https://github.com/epsagon/epsagon-node/blob/master/test/unit_tests/events/aws_v3.test.js

There is already a test to some non-existing-sns-topic that check we create trace for 'publish' so it won't be hard to add another one.

Thanks!

**Comment by ymwjbxxq** [comment]
I did for the v2, but I can add the v3 support as well. Good point.

**Comment by ymwjbxxq** [comment]
@haddasbronfman I added the unit tests and made the response for the v3 like the v2, but I have my doubts on this part

```
requestHandler(operation, command, event) {
        switch (operation) {
        case 'publish': {
            const resource = event.getResource();
            const paramArn = command.input.TopicArn || command.input.TargetArn;
            resource.setName(`${paramArn.split(':').pop()}` || 'N/A');
            eventInterface.addToMetadata(event, {}, {
                'Notification Message': `${command.input.Message}`,
                'Notification Message Attributes': `${JSON.stringify(command.input.MessageAttributes)}`,
            });
            break;
        }
        default:
            break;
        }
    },
```

As you can see we have
```
            eventInterface.addToMetadata(event, {}, {
                'Notification Message': `${command.input.Message}`,
                'Notification Message Attributes': `${JSON.stringify(command.input.MessageAttributes)}`,
            });
```

Without typings, I cannot track where this is coming from, but I guess for the batch command, the .input.Message will not work.

I think we need an if, but could you please shed some light?

**Review by haddasbronfman — COMMENTED** [review]
Did you run this code and saw what is the value of 'input'? I think this is inevitable in this case.

**Comment by ymwjbxxq** [comment]
it will be undefined

The build has this error

Serverless Error ----------------------------------------
 
  An error occurred: SyncUnderscore2UnderscoreparamUnderscorenoUnderscorereturnLambdaFunction - Resource handler returned message: "Unzipped size must be smaller than 262144000 bytes (Service: Lambda, Status Code: 400, Request ID: 85e7e6a7-38a4-4ecb-8317-6eda472ea497, Extended Request ID: null)" (RequestToken: b1bfa85b-2fd0-27e5-70d8-02fbd6affa22, HandlerErrorCode: InvalidRequest).

**Review by haddasbronfman — COMMENTED** [review]
This is an error of your serverless which is apparently not related to our code. I suggest you use a small node app that just use the publishBatch command to test is. This way you won't fail on serverless issues. 

This is what I used when I wrote the instrumentation for 'publish' 

```
var params = {
    Message: 'MESSAGE_TEXT',
    TopicArn: 'myTopicArn',
};

const run =  epsagon.nodeWrapper( async() => {
    try {
        const snsClient = new SNSClient({ region: 'ap-southeast-1' });
        var data = await snsClient.send(new PublishCommand(params));
        console.log("Success.",  data);
        return data; 
    } catch (err) {
        console.log("Error", err.stack);
    }
  }); 

run();
```

**Comment by ymwjbxxq** [comment]
@haddasbronfman 

Maybe I miss something. I have run the code in a Lambda using my Epsagon account against Layer:epsagon-node-layer:315

Here the V3 trace (it does not show up in the trace list)

```
2021-11-23T15:01:40.807+01:00	2021-11-23T14:01:40.768Z c707d388-99ac-44e6-86b1-7c8fa0ea066d INFO [EPSAGON] [http] captured call sns.eu-central-1.amazonaws.com

2021-11-23T15:01:40.807+01:00	2021-11-23T14:01:40.807Z c707d388-99ac-44e6-86b1-7c8fa0ea066d INFO [EPSAGON] [http] filtered ignored hostname sns.eu-central-1.amazonaws.com

2021-11-23T15:01:41.307+01:00

2021-11-23T14:01:41.269Z	c707d388-99ac-44e6-86b1-7c8fa0ea066d	INFO	Success. {
  '$metadata': {
    httpStatusCode: 200,
    requestId: '54a6b200-fa8e-5643-869f-e8160c0b9fe6',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  Successful: [
    {
      Id: 'string',
      MessageId: 'cf775c6c-8f50-52ab-af24-067a79d5fb0e',
      SequenceNumber: undefined
    }
  ],
  Failed: []
}
2021-11-23T14:01:41.269Z c707d388-99ac-44e6-86b1-7c8fa0ea066d INFO Success. { '$metadata': { httpStatusCode: 200, requestId: '54a6b200-fa8e-5643-869f-e8160c0b9fe6', extendedRequestId: undefined, cfId: undefined, attempts: 1, totalRetryDelay: 0 }, Successful: [ { Id: 'string', MessageId: 'cf775c6c-8f50-52ab-af24-067a79d5fb0e', SequenceNumber: undefined } ], Failed: [] }

2021-11-23T15:01:41.307+01:00	2021-11-23T14:01:41.307Z c707d388-99ac-44e6-86b1-7c8fa0ea066d INFO [EPSAGON] user promise resolved (in then)

2021-11-23T15:01:41.308+01:00	2021-11-23T14:01:41.308Z c707d388-99ac-44e6-86b1-7c8fa0ea066d INFO [EPSAGON] Sending trace sync

2021-11-23T15:01:41.308+01:00	2021-11-23T14:01:41.308Z c707d388-99ac-44e6-86b1-7c8fa0ea066d INFO [EPSAGON] [K8S-LOGS] adding K8s metadata to trace

2021-11-23T15:01:41.327+01:00	2021-11-23T14:01:41.308Z c707d388-99ac-44e6-86b1-7c8fa0ea066d INFO [EPSAGON] [K8S-LOGS] invoking function: , time: Tue, 23 Nov 2021 14:01:41 GMT

2021-11-23T15:01:41.327+01:00	2021-11-23T14:01:41.327Z c707d388-99ac-44e6-86b1-7c8fa0ea066d INFO [EPSAGON] [K8S-LOGS] function: finished execution, result: undefined, time: Tue, 23 Nov 2021 14:01:41 GMT

2021-11-23T15:01:41.328+01:00	2021-11-23T14:01:41.328Z c707d388-99ac-44e6-86b1-7c8fa0ea066d INFO [EPSAGON] Posting trace to https://eu-central-1.tc.epsagon.com

2021-11-23T15:01:41.328+01:00

Copy
2021-11-23T14:01:41.328Z	c707d388-99ac-44e6-86b1-7c8fa0ea066d	INFO	[EPSAGON] trace: 
{
    "app_name": "epsagon-test",
    "token": "f16af22b-01b6-45b8-90d4-33cb1df9d2ab",
    "events": [
        {
            "id": "c707d388-99ac-44e6-86b1-7c8fa0ea066d",
            "start_time": 1637676100.509,
            "resource": {
                "name": "mylambda",
                "type": "lambda",
                "operation": "invoke",
                "metadata": {
                    "aws_account": "xxxxxx",
                    "cold_start": "true",
                    "function_version": "$LATEST",
                    "log_group_name": "/aws/lambda/mylambda",
                    "log_stream_name": "2021/11/23/[$LATEST]d40f5db3724f47828362b41adf192364",
                    "memory": "128",
                    "region": "eu-central-1",
                    "return_value": "{\"$metadata\":{\"httpStatusCode\":200,\"requestId\":\"54a6b200-fa8e-5643-869f-e8160c0b9fe6\",\"attempts\":1,\"totalRetryDelay\":0},\"Successful\":[{\"Id\":\"string\",\"MessageId\":\"cf775c6c-8f50-52ab-af24-067a79d5fb0e\"}],\"Failed\":[]}"
                }
            },
            "origin": "runner",
            "duration": 0.798,
            "error_code": 0,
            "exception": {}
        },
        {
            "id": "trigger-6f3866ce-f9a4-4ca1-ab08-f9e28a5f7619",
            "start_time": 1637676100.509,
            "resource": {
                "name": "trigger-mylambda",
                "type": "json",
                "operation": "Event",
                "metadata": {
                    "data": {
                        "key1": "value1",
                        "key2": "value2",
                        "key3": "value3"
                    }
                }
            },
            "origin": "trigger",
            "duration": 0,
            "error_code": 0,
            "exception": {}
        }
    ],
    "exceptions": [],
    "version": "0.0.0-development",
    "platform": "node 14.18.1"
}


2021-11-23T15:01:41.387+01:00	2021-11-23T14:01:41.367Z c707d388-99ac-44e6-86b1-7c8fa0ea066d INFO [EPSAGON] [http] captured call eu-central-1.tc.epsagon.com

2021-11-23T15:01:41.387+01:00	2021-11-23T14:01:41.387Z c707d388-99ac-44e6-86b1-7c8fa0ea066d INFO [EPSAGON] [http] filtered ignored hostname eu-central-1.tc.epsagon.com

2021-11-23T15:01:41.487+01:00	2021-11-23T14:01:41.468Z c707d388-99ac-44e6-86b1-7c8fa0ea066d INFO [EPSAGON] Trace posted!
```

Here the V2 trace (it is on the trace list but empty)
```
2021-11-23T13:30:57.638Z	c551d109-9413-4e03-9f0e-e9bfce6e76cf	INFO	Error TypeError: i.publishBatch is not a function
    at /var/task/epsagon.js:2:465464
    at Runtime.handler (/var/task/epsagon.js:2:82330)
    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)
2021-11-23T13:30:57.676Z	c551d109-9413-4e03-9f0e-e9bfce6e76cf	INFO	[EPSAGON] user promise resolved (in then)
2021-11-23T13:30:57.676Z	c551d109-9413-4e03-9f0e-e9bfce6e76cf	INFO	[EPSAGON] Sending trace sync
2021-11-23T13:30:57.697Z	c551d109-9413-4e03-9f0e-e9bfce6e76cf	INFO	[EPSAGON] Posting trace to https://eu-central-1.tc.epsagon.com
2021-11-23T13:30:57.716Z	c551d109-9413-4e03-9f0e-e9bfce6e76cf	INFO	[EPSAGON] trace: {
  "app_name": "mylambda",
  "token": "f16af22b-01b6-45b8-90d4-33cb1df9d2ab",
  "events": [
    {
      "id": "c551d109-9413-4e03-9f0e-e9bfce6e76cf",
      "start_time": 1637674257.637,
      "resource": {
        "name": "mylambda",
        "type": "lambda",
        "operation": "invoke",
        "metadata": {
          "aws_account": "XXXX",
          "cold_start": "true",
          "function_version": "$LATEST",
          "log_group_name": "/aws/lambda/mylambda",
          "log_stream_name": "2021/11/23/[$LATEST]55ce5c6d94d84deba54c0ed5add84fef",
          "memory": "128",
          "region": "eu-central-1",
          "return_value": "null"
        }
      },
      "origin": "runner",
      "duration": 0.039,
      "error_code": 0,
      "exception": {}
    },
    {
      "id": "trigger-691753e6-5d9d-4689-9ad1-ad6d9864e27c",
      "start_time": 1637674257.636,
      "resource": {
        "name": "trigger-mylambda",
        "type": "json",
        "operation": "Event",
        "metadata": {
          "data": {
            "key1": "value1",
            "key2": "value2",
            "key3": "value3"
          }
        }
      },
      "origin": "trigger",
      "duration": 0,
      "error_code": 0,
      "exception": {}
    }
  ],
  "exceptions": [],
  "version": "0.0.0-development",
  "platform": "node 14.18.1"
}
2021-11-23T13:30:57.719Z	c551d109-9413-4e03-9f0e-e9bfce6e76cf	INFO	[EPSAGON] [http] captured call eu-central-1.tc.epsagon.com
2021-11-23T13:30:57.756Z	c551d109-9413-4e03-9f0e-e9bfce6e76cf	INFO	[EPSAGON] [http] filtered ignored hostname eu-central-1.tc.epsagon.com
2021-11-23T13:30:58.059Z	c551d109-9413-4e03-9f0e-e9bfce6e76cf	INFO	[EPSAGON] Trace posted!
``` 

I am a bit lost. What I usually do for testing is:
- run "build:dev"
- copy the files into my lambda replacing the current epsagon ones
- deploy my lambda
- run it and see the result of the trace


The version that use aws-sdk v2 is throwing 
Error TypeError: i.publishBatch is not a function
    at /var/task/epsagon.js:2:465464
    at Runtime.handler (/var/task/epsagon.js:2:82330)
    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)
    
This is my test
``` 
import epsagon from "epsagon";
//import { SNSClient, PublishBatchCommand, PublishBatchCommandInput, PublishBatchRequestEntry } from "@aws-sdk/client-sns";
import SNS from "aws-sdk/clients/sns";

epsagon.init({
  token: process.env.EPSAGON_TOKEN,
  appName: `mylambda`,
  metadataOnly: false,
});


//V3
// export const startExecution: any = epsagon.lambdaWrapper(async (event: any): Promise<any> => {
//   try {
//     const snsClient = new SNSClient({ region: 'eu-central-1' });
//     const entry: PublishBatchRequestEntry = {
//       Id: "string",
//       Message: "string",
//     };
//     const params: PublishBatchCommandInput = {
//       PublishBatchRequestEntries: [entry],
//       TopicArn: "arn:aws:sns:eu-central-1:XXXX:my-topic",
//     };
//     const data = await snsClient.send(new PublishBatchCommand(params));
//     console.log("Success.", data);
//     return data;
//   } catch (err) {
//     console.log("Error", err.stack);
//   }
// });

//V2
export const startExecution: any = epsagon.lambdaWrapper(async (event: any): Promise<any> => {
  try {
    const entry = {
      Id: "string",
      Message: "string",
    };
    const params = {
      PublishBatchRequestEntries: [entry],
      TopicArn: "arn:aws:sns:eu-central-1:XXXX:my-topic",
    };
    const sns = new SNS({
      region: process.env.AWS_REGION,
      maxRetries: 10,
      httpOptions: {
        timeout: 1000,
      },
    });
    const data = await sns.publishBatch(params).promise();
    console.log("Success.", data);
    return data;
  } catch (err) {
    console.log("Error", err.stack);
  }
});
``` 

Could you please help me to understand what is wrong?

**Comment by ymwjbxxq** [comment]
found the issue
SNS Batch has been introduced in version 2.1031.0

Lambda runtime is 2.1001.0

and this explains the error in the aws-sdk v2

It cannot be used. I can revert it or close this MR and I will resend it over when AWS update the runtime

**Review by haddasbronfman — COMMENTED** [review]
found it now too :)
I just took your code and managed to reproduced your error, but when I updated the aws-sdk to latest version (2.1034.0) it worked :)

why can't you stay with version 2.1031.0 and above?

**Comment by ymwjbxxq** [comment]
Until the AWS-SDK in the lambda runtime is 2.1001.0, we can not add the publishBatch because most of the time, you are not packing the AWS-SDK, and this is why it was failing. 

With the v3 that is not part of the lambda runtime instead, we can support it, but from my tests, I cannot see anything showing up in the Epsagon console.

**Pull request closed without merging**
