### PR TITLE
fix(require): fixing tryRequire for webpack

### PR DESCRIPTION
**Pull request by galbash**
Forces webpack to use external require if not found in webpack require

### CODE REVIEW

**Comment by tripodsan** [comment]
@galbash Nice find! Works for me.

**Comment by galbash** [comment]
Great! I will update it today with some more content (currently it only finds moduled which are not bundled in webpack, so you won't be able to instrument http for exmaple, will try to find a fix for that)

**Comment by galbash** [comment]
@tripodsan I updated the PR, currently (after a lot of webpack-wrestling) it should work, but we will only instrument external modules. So if you want to instrument pg, for example, you must specify it as external in your webpack config. Does that sound reasonable?

@ranrib would love for your take on this as well

**Review by ranrib — APPROVED** [review]

**Comment by galbash** [comment]
@tripodsan just a head's up that the issue is merged to `master` and a version should be released soon :)

**Pull request merged**
