### PR TITLE
fix(wsk): fix hanging openwhisk actions

### PR DESCRIPTION
**Pull request by tripodsan**
I don't really understand why, but changing the `finally()` function from returning a value to a block solves our hanging actions problems.....maybe because returning a promise from the finally block makes it hanging but when it's returned into the same scope, it is not? 

maybe something todo with unresolved promises and node 12?

### CODE REVIEW

**Comment by enoodle** [comment]
@tripodsan Thanks for that, we are reviewing.

**Review by ranrib — APPROVED** [review]

**Review by enoodle — APPROVED** [review]

**Comment by tripodsan** [comment]
BTW, I'm not sure if this was a good fix. it turns out, that there is different behaviour on macos and linux (I didn't test windows). 

with this new version on macos, the trace is sent before the response is returned.
but on linux, the trace is send after the response is returned. 

I'll do some more testing....

**Comment by tripodsan** [comment]
@ranrib it would be cool, if someone from your team could investigate our _linux_ problem. it is easily reproducible here: https://github.com/adobe/helix-epsagon/issues/157

**Comment by ranrib** [comment]
Yes we will investigate this

**Pull request merged**
