### PR TITLE
Feat : integrate eventbridge for aws sdk v3

### LINKED ISSUE #572: Eventbridge operations for the AWS SDK V3 are not supported
Events put on an Eventbridge bus with the sdk v3 are not traced.

To compare the sdk v2 and v3 : 

```ts
import { APIGatewayProxyEvent } from 'aws-lambda';
import EventBridgeV2 from 'aws-sdk/clients/eventbridge';
import { EventBridge, PutEventsCommand } from '@aws-sdk/client-eventbridge';
import epsagon from 'epsagon';

const eventBridgeV2 = new EventBridgeV2();
const eventBridgeV3 = new EventBridge({});

epsagon.init({token, 'Demo-Epsagon'});

const demoEpsagon = async (event: APIGatewayProxyEvent) => {
  await eventBridgeV2
    .putEvents({
      Entries: [
        {
          Source: 'demo-epsagon-V2',
          DetailType: 'TEST',
          Detail: JSON.stringify({}),
          EventBusName: 'demo-epsagon',
        },
      ],
    })
    .promise();
  await eventBridgeV3.send(
    new PutEventsCommand({
      Entries: [
        {
          Source: 'demo-epsagon-V3',
          DetailType: 'TEST',
          Detail: JSON.stringify({}),
          EventBusName: 'demo-epsagon',
        },
      ],
    }),
  );
};

export const main = epsagon.lambdaWrapper(demoEpsagon);
```

### PR DESCRIPTION
**Pull request by guillaumeduboc**
Fix #572 
This is the continuation of #573

### CODE REVIEW

**Comment by arbiv** [comment]
@osherv is OOO. @nemoshlag can you please review this?

**Review by nemoshlag — APPROVED** [review]

**Comment by guillaumeduboc** [comment]
Thank you @nemoshlag for approving the PR. Can I merge it?

**Comment by nemoshlag** [comment]
Oops merging it now, I'll ping you once it's published @guillaumeduboc

**Pull request merged**
